In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

from datetime import *
from datetime import time
from astral import Astral

In [12]:
sleep_df = pd.read_excel('../data/cleaned_sleep_data.xlsx', index_col=0)
sleep_df['Start Date'] = pd.to_datetime(sleep_df['Start Date']).dt.date
sleep_df['Start Time'] = pd.to_datetime(sleep_df['Start Time']).dt.time


steps_df = pd.read_excel('../data/cleaned_daily_step_data.xlsx', index_col=0)
steps_df['Date'] = pd.to_datetime(steps_df['Date']).dt.date

weather_df = pd.read_excel('../data/cleaned_weather_data.xlsx', index_col=0)
weather_df['Date'] = pd.to_datetime(weather_df['Date']).dt.date

## Merging sleep and steps

In [13]:
merged_df = pd.merge(sleep_df, steps_df, how='inner', left_on='Start Date', right_on='Date')
merged_df.drop(columns='Date', inplace=True)
merged_df

,Start Date,Start Time,End Date,End Time,Sleep Quality,Regularity,Alarm mode,Movements per hour,Time in bed (seconds),Time asleep (seconds),Time before sleep (seconds),Did snore,Snore time,Previous Night Sleep Quality Score,Good Sleep?,Steps
0,2019-12-24,22:27:42,2019-12-25,06:54:53,86,73,Normal,17.6,30430.2,27488.6,1521.5,True,0.0,86.204221,1,1155
1,2019-12-25,23:05:37,2019-12-26,08:29:54,88,82,Normal,39.9,33856.3,28890.7,1241.4,True,0.0,86.000000,1,1267
2,2019-12-26,23:00:29,2019-12-27,07:32:20,90,86,Normal,27.5,30710.7,28151.5,1535.5,True,0.0,88.000000,1,241
3,2019-12-27,22:44:54,2019-12-28,07:30:47,92,90,Normal,23.9,31553.8,28819.1,1157.0,True,0.0,90.000000,1,5310
4,2019-12-28,01:15:26,2019-12-29,08:15:27,78,87,Normal,25.8,25201.2,22093.1,1092.1,True,0.0,92.000000,0,2580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,2022-04-03,00:10:50,2022-04-04,07:07:47,71,87,Normal,65.8,25017.8,21015.0,2084.8,True,600.0,89.000000,0,8514
717,2022-04-04,23:42:58,2022-04-05,07:30:41,78,87,Normal,72.0,28062.7,21608.3,1122.5,True,240.0,71.000000,0,677
718,2022-04-05,23:22:47,2022-04-06,07:30:30,91,90,Normal,41.1,29263.6,21264.9,1560.7,True,420.0,78.000000,1,6542
719,2022-04-06,23:16:06,2022-04-07,07:40:20,69,96,Normal,123.3,30253.5,27934.0,2319.4,True,1063.3,91.000000,0,1961
720,2022-04-07,23:41:14,2022-04-08,08:45:34,100,94,Normal,31.9,32660.1,26019.2,2939.4,True,480.0,69.000000,1,6950

## Merging weather

In [14]:
# Weather data merge
display(weather_df)

merged_df = pd.merge(merged_df, weather_df, how='inner', left_on='Start Date', right_on='Date')
display(merged_df)

,Date,visibility_distance_mean,visibility_distance_min,visibility_distance_max,air_temperature_mean,air_temperature_min,air_temperature_max,humidity_max,humidity_min,humidity_mean
0,2017-01-01,18333.333333,14000.0,23000.0,3.966667,3.7,4.2,NaN,NaN,NaN
1,2017-01-02,17735.000000,7000.0,30000.0,1.950000,-3.0,5.0,100.0,70.0,86.125000
2,2017-01-03,17171.114286,7000.0,35000.0,1.176364,-5.0,5.0,100.0,75.0,88.414634
3,2017-01-04,20573.978723,9999.0,45000.0,4.775926,-3.0,8.1,93.0,61.0,77.981481
4,2017-01-05,14255.555556,1900.0,21000.0,-1.327778,-6.0,6.0,100.0,65.0,88.481481
...,...,...,...,...,...,...,...,...,...,...
1909,2022-03-31,18408.439394,5000.0,50000.0,2.851515,0.0,7.1,87.0,45.0,71.515152
1910,2022-04-01,19304.888889,9999.0,55000.0,3.204167,-3.0,8.1,93.0,31.0,69.680556
1911,2022-04-02,16419.507692,4600.0,55000.0,1.666154,-4.5,9.0,96.0,35.0,76.723077
1912,2022-04-03,14379.986111,800.0,50000.0,3.022222,-5.0,10.0,98.0,43.0,69.291667
1913,2022-04-04,15780.984615,3100.0,60000.0,9.403077,4.7,14.1,94.0,65.0,81.523077

,Start Date,Start Time,End Date,End Time,Sleep Quality,Regularity,Alarm mode,Movements per hour,Time in bed (seconds),Time asleep (seconds),...,Date,visibility_distance_mean,visibility_distance_min,visibility_distance_max,air_temperature_mean,air_temperature_min,air_temperature_max,humidity_max,humidity_min,humidity_mean
0,2019-12-24,22:27:42,2019-12-25,06:54:53,86,73,Normal,17.6,30430.2,27488.6,...,2019-12-24,13424.388889,3100.0,60000.0,9.001389,7.0,11.0,100.0,71.0,86.208333
1,2019-12-25,23:05:37,2019-12-26,08:29:54,88,82,Normal,39.9,33856.3,28890.7,...,2019-12-25,18217.458333,300.0,65000.0,3.379167,-2.0,8.4,100.0,69.0,86.138889
2,2019-12-26,23:00:29,2019-12-27,07:32:20,90,86,Normal,27.5,30710.7,28151.5,...,2019-12-26,11234.250000,2500.0,50000.0,6.581944,-2.0,10.3,100.0,81.0,91.625000
3,2019-12-27,22:44:54,2019-12-28,07:30:47,92,90,Normal,23.9,31553.8,28819.1,...,2019-12-27,9920.472222,4500.0,26000.0,6.386111,5.9,8.0,97.0,87.0,92.458333
4,2019-12-28,01:15:26,2019-12-29,08:15:27,78,87,Normal,25.8,25201.2,22093.1,...,2019-12-28,9042.666667,2700.0,23000.0,7.656944,6.7,9.0,100.0,81.0,90.763889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2022-03-26,23:03:02,2022-03-27,08:30:27,94,90,Normal,41.2,30444.8,25269.2,...,2022-03-26,11156.527778,2700.0,35000.0,8.956944,-1.0,17.1,97.0,32.0,65.500000
713,2022-04-01,00:18:20,2022-04-02,08:49:02,87,91,Normal,67.7,30642.1,25943.7,...,2022-04-01,19304.888889,9999.0,55000.0,3.204167,-3.0,8.1,93.0,31.0,69.680556
714,2022-04-02,23:12:49,2022-04-03,08:34:54,89,90,Normal,75.8,33724.9,31251.8,...,2022-04-02,16419.507692,4600.0,55000.0,1.666154,-4.5,9.0,96.0,35.0,76.723077
715,2022-04-03,00:10:50,2022-04-04,07:07:47,71,87,Normal,65.8,25017.8,21015.0,...,2022-04-03,14379.986111,800.0,50000.0,3.022222,-5.0,10.0,98.0,43.0,69.291667
716,2022-04-04,23:42:58,2022-04-05,07:30:41,78,87,Normal,72.0,28062.7,21608.3,...,2022-04-04,15780.984615,3100.0,60000.0,9.403077,4.7,14.1,94.0,65.0,81.523077

## Adding daylight hours

In [15]:
def get_daylight_hours(row):

    a = Astral()
    a.solar_depression = 'civil'
    city = a['London']
    sun = city.sun(date=row['Date'], local=True)
    
    daylight_amount = sun['sunset'] - sun['sunrise']
    daylight_hours = (daylight_amount.seconds) /3600
    
    return daylight_hours

merged_df['Daylight Hours'] = merged_df.apply(get_daylight_hours, axis=1)

## Adding day data

In [16]:
merged_df.insert(loc=2, column='Day', value=pd.to_datetime(merged_df['Date']).dt.dayofweek)
day_df = pd.get_dummies(merged_df.Day, prefix='Day')
merged_df = pd.merge(merged_df, day_df, how='inner', left_index=True, right_index=True)
merged_df

,Start Date,Start Time,Day,End Date,End Time,Sleep Quality,Regularity,Alarm mode,Movements per hour,Time in bed (seconds),...,humidity_min,humidity_mean,Daylight Hours,Day_0,Day_1,Day_2,Day_3,Day_4,Day_5,Day_6
0,2019-12-24,22:27:42,1,2019-12-25,06:54:53,86,73,Normal,17.6,30430.2,...,71.0,86.208333,7.832222,0,1,0,0,0,0,0
1,2019-12-25,23:05:37,2,2019-12-26,08:29:54,88,82,Normal,39.9,33856.3,...,69.0,86.138889,7.837778,0,0,1,0,0,0,0
2,2019-12-26,23:00:29,3,2019-12-27,07:32:20,90,86,Normal,27.5,30710.7,...,81.0,91.625000,7.844722,0,0,0,1,0,0,0
3,2019-12-27,22:44:54,4,2019-12-28,07:30:47,92,90,Normal,23.9,31553.8,...,87.0,92.458333,7.853889,0,0,0,0,1,0,0
4,2019-12-28,01:15:26,5,2019-12-29,08:15:27,78,87,Normal,25.8,25201.2,...,81.0,90.763889,7.864722,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2022-03-26,23:03:02,5,2022-03-27,08:30:27,94,90,Normal,41.2,30444.8,...,32.0,65.500000,12.583611,0,0,0,0,0,1,0
713,2022-04-01,00:18:20,4,2022-04-02,08:49:02,87,91,Normal,67.7,30642.1,...,31.0,69.680556,12.979167,0,0,0,0,1,0,0
714,2022-04-02,23:12:49,5,2022-04-03,08:34:54,89,90,Normal,75.8,33724.9,...,35.0,76.723077,13.045000,0,0,0,0,0,1,0
715,2022-04-03,00:10:50,6,2022-04-04,07:07:47,71,87,Normal,65.8,25017.8,...,43.0,69.291667,13.110556,0,0,0,0,0,0,1
716,2022-04-04,23:42:58,0,2022-04-05,07:30:41,78,87,Normal,72.0,28062.7,...,65.0,81.523077,13.176111,1,0,0,0,0,0,0

In [17]:
columns_to_drop = ['Start Time', 'Day', 'End Date', 'End Time',
                   'Alarm mode', 'Movements per hour', 'Sleep Quality',
                   'Time in bed (seconds)', 'Time asleep (seconds)',
                   'Time before sleep (seconds)', 'Did snore', 'Snore time',
                   'Date']

merged_df = merged_df.drop(columns=columns_to_drop)
merged_df.reset_index(inplace=True, drop=True)
merged_df

,Start Date,Regularity,Previous Night Sleep Quality Score,Good Sleep?,Steps,visibility_distance_mean,visibility_distance_min,visibility_distance_max,air_temperature_mean,air_temperature_min,...,humidity_min,humidity_mean,Daylight Hours,Day_0,Day_1,Day_2,Day_3,Day_4,Day_5,Day_6
0,2019-12-24,73,86.204221,1,1155,13424.388889,3100.0,60000.0,9.001389,7.0,...,71.0,86.208333,7.832222,0,1,0,0,0,0,0
1,2019-12-25,82,86.000000,1,1267,18217.458333,300.0,65000.0,3.379167,-2.0,...,69.0,86.138889,7.837778,0,0,1,0,0,0,0
2,2019-12-26,86,88.000000,1,241,11234.250000,2500.0,50000.0,6.581944,-2.0,...,81.0,91.625000,7.844722,0,0,0,1,0,0,0
3,2019-12-27,90,90.000000,1,5310,9920.472222,4500.0,26000.0,6.386111,5.9,...,87.0,92.458333,7.853889,0,0,0,0,1,0,0
4,2019-12-28,87,92.000000,0,2580,9042.666667,2700.0,23000.0,7.656944,6.7,...,81.0,90.763889,7.864722,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2022-03-26,90,86.204221,1,11477,11156.527778,2700.0,35000.0,8.956944,-1.0,...,32.0,65.500000,12.583611,0,0,0,0,0,1,0
713,2022-04-01,91,86.204221,1,3700,19304.888889,9999.0,55000.0,3.204167,-3.0,...,31.0,69.680556,12.979167,0,0,0,0,1,0,0
714,2022-04-02,90,87.000000,1,5836,16419.507692,4600.0,55000.0,1.666154,-4.5,...,35.0,76.723077,13.045000,0,0,0,0,0,1,0
715,2022-04-03,87,89.000000,0,8514,14379.986111,800.0,50000.0,3.022222,-5.0,...,43.0,69.291667,13.110556,0,0,0,0,0,0,1
716,2022-04-04,87,71.000000,0,677,15780.984615,3100.0,60000.0,9.403077,4.7,...,65.0,81.523077,13.176111,1,0,0,0,0,0,0

In [18]:
merged_df.to_excel('../data/cleaned_merged_df.xlsx')